[display_detection]
model_path = "models/display_detection.tflite"
input_size = 320

[reading_detection]
model_path = "models/reading_detection.tflite"

[reading_ocr]
model_path = "models/reading_ocr.tflite"
input_size.x = 200
input_size.y = 31
alphabet = "0123456789abcdefghijklmnopqrstuvwxyz."